# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29170c79e2417ea68f641b07671d115d2c94cd09f706d155b9e108f9e84c337a6cc8305cc64265e4e95d7cd2140398f2e2f6cd311847583f48796d74dab2a5e4

test:
  secret_key_base: f842b3f830fde7be611b803c15c9635ec17667f493b07e75e32b07d5631093515f7fe14fae08eff0b0798b7760e2e6c7bff0b27d3723a7d1f5d21b1d8ba226da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
